from pathlib import Path

class DatasetType:
    TRAIN = 'train'
    TEST = 'test'
    VALID = 'valid'


class DatasetTypeTargets:
    TRAIN = 'train_targets'
    TEST = 'test_targets'
    VALID = 'valid_targets'


class Paths:
    TRAIN_DIR = 'train'
    TRAIN_TARGETS_DIR = 'train_targets'
    TEST_DIR = 'test'
    TEST_TARGETS_DIR = 'test_targets'
    VALID_DIR = 'valid'
    VALID_TARGETS_DIR = 'valid_targets'

    IMAGES_DIR = 'IMAGES'
    MASKS_DIR = 'MASKS'
    REFERENCE_SEGMENTATIONS_DIR = 'REFERENCE_SEGMENTATIONS'

    PROJECT_DIR = Path.cwd().parent
    DATA_DIR = PROJECT_DIR / "data"
    CONFIG_PATH = PROJECT_DIR / 'config.json'

    CHUNKS_PATH = DATA_DIR / 'chunks'
    INPUT_PATH = DATA_DIR / 'input'
    MASKS_PATH = DATA_DIR / MASKS_DIR
    IMAGES_PATH = DATA_DIR / IMAGES_DIR
    NIFTI_PATH = DATA_DIR / 'nifti'
    NPY_PATH = DATA_DIR / 'npy'
    MASK_FILE_PATTERN = 'MASK_*'

    # Directories' paths
    CHUNKS_TEST_PATH = CHUNKS_PATH / TEST_DIR
    CHUNKS_TEST_TARGETS_PATH = CHUNKS_PATH / TEST_TARGETS_DIR
    CHUNKS_TRAIN_PATH = CHUNKS_PATH / TRAIN_DIR
    CHUNKS_TRAIN_TARGETS_PATH = CHUNKS_PATH / TRAIN_TARGETS_DIR
    CHUNKS_VALID_PATH = CHUNKS_PATH / VALID_DIR
    CHUNKS_VALID_TARGETS_PATH = CHUNKS_PATH / VALID_TARGETS_DIR

    INPUT_TEST_PATH = INPUT_PATH / TEST_DIR
    INPUT_TEST_TARGETS_PATH = INPUT_PATH / TEST_TARGETS_DIR
    INPUT_TRAIN_PATH = INPUT_PATH / TRAIN_DIR
    INPUT_TRAIN_TARGETS_PATH = INPUT_PATH / TRAIN_TARGETS_DIR
    INPUT_VALID_PATH = INPUT_PATH / VALID_DIR
    INPUT_VALID_TARGETS_PATH = INPUT_PATH / VALID_TARGETS_DIR

    NIFTI_IMAGES_PATH = NIFTI_PATH / IMAGES_DIR
    NIFTI_MASKS_PATH = NIFTI_PATH / MASKS_DIR

    NPY_IMAGES_PATH = NPY_PATH / IMAGES_DIR
    NPY_MASKS_PATH = NPY_PATH / MASKS_DIR

    REFERENCE_SEGMENTATIONS_PATH = DATA_DIR / REFERENCE_SEGMENTATIONS_DIR


BATCH_SIZE = 'batch_size'
CHUNK_SIZE = 'chunk_size'
