from pathlib import Path

# Directories names
DATA_DIR = Path('PATH_TO_DIR_WITH_IMAGES_AND_REFERENCE_SEGMENTATIONS_DIRS')


class DatasetType:
    TRAIN = 'train'
    TEST = 'test'
    VALID = 'valid'


class DatasetTypeTargets:
    TRAIN = 'train_targets'
    TEST = 'test_targets'
    VALID = 'valid_targets'


IMAGES_DIR = 'IMAGES'
MASKS_DIR = 'MASKS'
REFERENCE_SEGMENTATIONS_DIR = 'REFERENCE_SEGMENTATIONS'

CHUNKS_PATH = DATA_DIR / 'chunks'
INPUT_PATH = DATA_DIR / 'input'
NIFTI_PATH = DATA_DIR / 'nifti'
NPY_PATH = DATA_DIR / 'npy'

# Directories' paths
CHUNKS_TEST_PATH = CHUNKS_PATH / DatasetType.TEST
CHUNKS_TEST_TARGETS_PATH = CHUNKS_PATH / DatasetTypeTargets.TEST
CHUNKS_TRAIN_PATH = CHUNKS_PATH / DatasetType.TRAIN
CHUNKS_TRAIN_TARGETS_PATH = CHUNKS_PATH / DatasetTypeTargets.TRAIN
CHUNKS_VALID_PATH = CHUNKS_PATH / DatasetType.VALID
CHUNKS_VALID_TARGETS_PATH = CHUNKS_PATH / DatasetTypeTargets.VALID

INPUT_TEST_PATH = INPUT_PATH / DatasetType.TEST
INPUT_TEST_TARGETS_PATH = INPUT_PATH / DatasetTypeTargets.TEST
INPUT_TRAIN_PATH = INPUT_PATH / DatasetType.TRAIN
INPUT_TRAIN_TARGETS_PATH = INPUT_PATH / DatasetTypeTargets.TRAIN
INPUT_VALID_PATH = INPUT_PATH / DatasetType.VALID
INPUT_VALID_TARGETS_PATH = INPUT_PATH / DatasetTypeTargets.VALID

NIFTI_IMAGES_PATH = NIFTI_PATH / IMAGES_DIR
NIFTI_MASKS_PATH = NIFTI_PATH / MASKS_DIR

NPY_IMAGES_PATH = NPY_PATH / IMAGES_DIR
NPY_MASKS_PATH = NPY_PATH / MASKS_DIR
