from pathlib import Path

# Directories names
DATA_DIR = Path('data')

TRAIN_DIR = 'train'
TRAIN_TARGETS_DIR = 'train_targets'
TEST_DIR = 'test'
TEST_TARGETS_DIR = 'test_targets'
VALID_DIR = 'valid'
VALID_TARGETS_DIR = 'valid_targets'

IMAGES_DIR = 'IMAGES'
MASKS_DIR = 'MASKS'

CHUNKS_PATH = DATA_DIR/'chunks'
INPUT_PATH = DATA_DIR/'input'
NIFTI_PATH = DATA_DIR/'nifti'
NPY_PATH = DATA_DIR/'npy'

# Directories' paths
CHUCKS_TEST_PATH = CHUNKS_PATH/TEST_DIR
CHUCKS_TEST_TARGETS_PATH = CHUNKS_PATH/TEST_TARGETS_DIR
CHUCKS_TRAIN_PATH = CHUNKS_PATH/TRAIN_DIR
CHUCKS_TRAIN_TARGETS_PATH = CHUNKS_PATH/TRAIN_TARGETS_DIR
CHUCKS_VALID_PATH = CHUNKS_PATH/VALID_DIR
CHUCKS_VALID_TARGETS_PATH = CHUNKS_PATH/VALID_TARGETS_DIR

INPUT_TEST_PATH = INPUT_PATH/TEST_DIR
INPUT_TEST_TARGETS_PATH = INPUT_PATH/TEST_TARGETS_DIR
INPUT_TRAIN_PATH = INPUT_PATH/TRAIN_DIR
INPUT_TRAIN_TARGETS_PATH = INPUT_PATH/TRAIN_TARGETS_DIR
INPUT_VALID_PATH = INPUT_PATH/VALID_DIR
INPUT_VALID_TARGETS_PATH = INPUT_PATH/VALID_TARGETS_DIR

NIFTI_IMAGES_PATH = NIFTI_PATH/IMAGES_DIR
NIFTI_MASKS_PATH = NIFTI_PATH/MASKS_DIR

NPY_IMAGES_PATH = NPY_PATH/IMAGES_DIR
NPY_MASKS_PATH = NPY_PATH/MASKS_DIR
