from pathlib import Path

# Directories names
DATA_DIR = Path('/home/alikrz/Pulpit/MyStuff/cancer-detection/3d-cnn-prometheus/data')


class DatasetType:
    TRAIN_DIR = 'train'
    TEST_DIR = 'test'
    VALID_DIR = 'valid'


class DatasetTypeTargets:
    TRAIN_TARGETS_DIR = 'train_targets'
    TEST_TARGETS_DIR = 'test_targets'
    VALID_TARGETS_DIR = 'valid_targets'


IMAGES_DIR = 'IMAGES'
MASKS_DIR = 'MASKS'

CHUNKS_PATH = DATA_DIR / 'chunks'
INPUT_PATH = DATA_DIR / 'input'
NIFTI_PATH = DATA_DIR / 'nifti'
NPY_PATH = DATA_DIR / 'npy'

# Directories' paths
CHUNKS_TEST_PATH = CHUNKS_PATH / DatasetType.TEST_DIR
CHUNKS_TEST_TARGETS_PATH = CHUNKS_PATH / DatasetTypeTargets.TEST_TARGETS_DIR
CHUNKS_TRAIN_PATH = CHUNKS_PATH / DatasetType.TRAIN_DIR
CHUNKS_TRAIN_TARGETS_PATH = CHUNKS_PATH / DatasetTypeTargets.TRAIN_TARGETS_DIR
CHUNKS_VALID_PATH = CHUNKS_PATH / DatasetType.VALID_DIR
CHUNKS_VALID_TARGETS_PATH = CHUNKS_PATH / DatasetTypeTargets.VALID_TARGETS_DIR

INPUT_TEST_PATH = INPUT_PATH / DatasetType.TEST_DIR
INPUT_TEST_TARGETS_PATH = INPUT_PATH / DatasetTypeTargets.TEST_TARGETS_DIR
INPUT_TRAIN_PATH = INPUT_PATH / DatasetType.TRAIN_DIR
INPUT_TRAIN_TARGETS_PATH = INPUT_PATH / DatasetTypeTargets.TRAIN_TARGETS_DIR
INPUT_VALID_PATH = INPUT_PATH / DatasetType.VALID_DIR
INPUT_VALID_TARGETS_PATH = INPUT_PATH / DatasetTypeTargets.VALID_TARGETS_DIR

NIFTI_IMAGES_PATH = NIFTI_PATH / IMAGES_DIR
NIFTI_MASKS_PATH = NIFTI_PATH / MASKS_DIR

NPY_IMAGES_PATH = NPY_PATH / IMAGES_DIR
NPY_MASKS_PATH = NPY_PATH / MASKS_DIR
